package ReversibleStatements.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class ReversibleStatementList_Constraints extends BaseConstraintsDescriptor {
  /*package*/ ReversibleStatementList_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.ReversibleStatementList$qe, initContext);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ReversibleStatementList$qe = MetaAdapterFactory.getConcept(0xf75f9e3fb00b4997L, 0x8af20a8ce6b25221L, 0x3a16e3a9c7ad9955L, "ReversibleStatements.structure.ReversibleStatementList");
  }
}
