package ReversibleExpressions.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.AbstractIntentionDescriptor;
import jetbrains.mps.openapi.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.openapi.intentions.IntentionExecutable;
import jetbrains.mps.openapi.intentions.Kind;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import java.util.Collections;
import jetbrains.mps.intentions.AbstractIntentionExecutable;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import jetbrains.mps.openapi.intentions.IntentionDescriptor;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public final class toggleCastToInt_Intention extends AbstractIntentionDescriptor implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;

  public toggleCastToInt_Intention() {
    super(Kind.NORMAL, false, new SNodePointer("r:ffac3c8b-1251-4a0c-8bd6-5bf800d7a9eb(ReversibleExpressions.intentions)", "7533755140569672022"));
  }

  @Override
  public String getPresentation() {
    return "toggleCastToInt";
  }

  @Override
  public boolean isSurroundWith() {
    return false;
  }

  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new IntentionImplementation());
    }
    return myCachedExecutable;
  }
  /*package*/ final class IntentionImplementation extends AbstractIntentionExecutable {
    public IntentionImplementation() {
    }

    @Override
    public String getDescription(final SNode node, final EditorContext editorContext) {
      return "EXPR: " + ("Add Rounding Operation");
    }

    @Override
    public void execute(final SNode node, final EditorContext editorContext) {
      SPropertyOperations.setEnum(node, PROPS.operation$a77l, 0x232671d0f97dd9ebL, "round");
    }

    @Override
    public boolean isApplicable(final SNode node, final EditorContext editorContext) {
      if (!(isApplicableToNode(node, editorContext))) {
        return false;
      }
      return true;
    }

    private boolean isApplicableToNode(final SNode node, final EditorContext editorContext) {
      return (SPropertyOperations.getEnum(node, PROPS.operation$a77l) == null) || SEnumOperations.isMember(SPropertyOperations.getEnum(node, PROPS.operation$a77l), 0x232671d0f97dd8c5L);
    }


    @Override
    public IntentionDescriptor getDescriptor() {
      return toggleCastToInt_Intention.this;
    }

  }

  private static final class PROPS {
    /*package*/ static final SProperty operation$a77l = MetaAdapterFactory.getProperty(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x688d46628178f19aL, 0x232671d0f97ddd5cL, "operation");
  }
}
