package ReversibleExpressions.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import ReversibleExpressions.behavior.IBinArithmetic__BehaviorDescriptor;
import ReversibleExpressions.behavior.BinaryExpression__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.traceable.behavior.TraceableConcept__BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class BinaryExpression_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.createPositionInfo();

    boolean isDestructive = SNodeOperations.isInstanceOf(ctx.getPrimaryInput(), CONCEPTS.IDestructiveOperation$SP) && !(SPropertyOperations.getBoolean(ctx.getPrimaryInput(), PROPS.disableStateSaving$rNjh));

    // if the binary expression is a Div-, Minus-, Multi- or PlusExpression and it is the right side of a direct assignment expression, it must not be reversed

    boolean reversibilityNotNeeded = (SNodeOperations.isInstanceOf(ctx.getPrimaryInput(), CONCEPTS.IBinArithmetic$8B) && (boolean) IBinArithmetic__BehaviorDescriptor.checkIfRightSideOfDirectAssignment_id79P5B3Nkar8.invoke(SNodeOperations.cast(ctx.getPrimaryInput(), CONCEPTS.IBinArithmetic$8B))) || (boolean) BinaryExpression__BehaviorDescriptor.isLoopCondition_id7FTvvGQ_l_a.invoke(ctx.getPrimaryInput());


    if (isDestructive && !(SPropertyOperations.getBoolean(ctx.getPrimaryInput(), PROPS.isForward$pAg5))) {
      return;
    }

    if ((boolean) BinaryExpression__BehaviorDescriptor.requiresParensAroundArgument_id3_qrK00j4rM.invoke(ctx.getPrimaryInput(), SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.left$KPKR))) {
      tgs.append("(");
      tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.left$KPKR));
      tgs.append(")");
    } else {
      tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.left$KPKR));
    }

    if (SPropertyOperations.getBoolean(ctx.getPrimaryInput(), PROPS.isForward$pAg5) || reversibilityNotNeeded) {
      tgs.append(" ");
      tgs.append(SConceptOperations.conceptAlias(SNodeOperations.getConcept(ctx.getPrimaryInput())));
      tgs.append(" ");
    } else if (!(isDestructive)) {
      tgs.append(" ");
      tgs.append(BinaryExpression__BehaviorDescriptor.getReversedOperator_id4e6KBjCJeOF.invoke(ctx.getPrimaryInput()));
      tgs.append(" ");
    } else {
      tgs.append(" = ");
    }

    if (SPropertyOperations.getBoolean(ctx.getPrimaryInput(), PROPS.isForward$pAg5) || !(isDestructive)) {
      if ((boolean) BinaryExpression__BehaviorDescriptor.requiresParensAroundArgument_id3_qrK00j4rM.invoke(ctx.getPrimaryInput(), SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.right$KPZS))) {
        tgs.append("(");
        tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.right$KPZS));
        tgs.append(")");
      } else {
        tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.right$KPZS));
      }
    }
    if (tgs.needPositions()) {
      tgs.fillPositionInfo(TraceableConcept__BehaviorDescriptor.getTraceableProperty_id4pl5GY7LKmH.invoke(SNodeOperations.cast(ctx.getPrimaryInput(), CONCEPTS.TraceableConcept$L)));
    }
  }

  private static final class PROPS {
    /*package*/ static final SProperty disableStateSaving$rNjh = MetaAdapterFactory.getProperty(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x7af69e2e83a1ba32L, 0x3bc958288c005be7L, "disableStateSaving");
    /*package*/ static final SProperty isForward$pAg5 = MetaAdapterFactory.getProperty(0xf75f9e3fb00b4997L, 0x8af20a8ce6b25221L, 0x56ee1731ff59bedbL, 0x56ee1731ff5a116fL, "isForward");
  }

  private static final class CONCEPTS {
    /*package*/ static final SInterfaceConcept IDestructiveOperation$SP = MetaAdapterFactory.getInterfaceConcept(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x27d0c8e745a2c78dL, "ReversibleExpressions.structure.IDestructiveOperation");
    /*package*/ static final SInterfaceConcept IBinArithmetic$8B = MetaAdapterFactory.getInterfaceConcept(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x72751670f350a6b0L, "ReversibleExpressions.structure.IBinArithmetic");
    /*package*/ static final SInterfaceConcept TraceableConcept$L = MetaAdapterFactory.getInterfaceConcept(0x9ded098bad6a4657L, 0xbfd948636cfe8bc3L, 0x465516cf87c705a3L, "jetbrains.mps.lang.traceable.structure.TraceableConcept");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink left$KPKR = MetaAdapterFactory.getContainmentLink(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x7af69e2e83a1ba34L, 0x7af69e2e83a1ba40L, "left");
    /*package*/ static final SContainmentLink right$KPZS = MetaAdapterFactory.getContainmentLink(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x7af69e2e83a1ba34L, 0x7af69e2e83a1ba41L, "right");
  }
}
