package DESL.textGen;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import com.mbeddr.core.modules.behavior.ITypeDeclaration__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SConcept;

public abstract class ROSSUtils {
  public static void rossEventHandler(SNode deslModel, SNode c, final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);

    tgs.append("void ");
    tgs.append(SPropertyOperations.getString(deslModel, PROPS.name$MnvL));
    tgs.append("_");
    tgs.append(SPropertyOperations.getString(c, PROPS.name$MnvL));
    tgs.append("_event(");
    tgs.appendNode(ITypeDeclaration__BehaviorDescriptor.createType_id3o2OLGv7CoR.invoke(SLinkOperations.getTarget(c, LINKS.stateStruct$NqNO)));
    tgs.append(" *state, tw_bf *bf, ");
    tgs.appendNode(ITypeDeclaration__BehaviorDescriptor.createType_id3o2OLGv7CoR.invoke(SLinkOperations.getTarget(deslModel, LINKS.messageStruct$xVlJ)));
    tgs.append(" *content, tw_lp *lp)");
    tgs.newLine();
    tgs.append("{");
    tgs.newLine();

    ctx.getBuffer().area().increaseIndent();
    // create "me" and "now" variables
    tgs.indent();
    tgs.append("tw_lpid me = lp->gid;");
    tgs.newLine();
    tgs.indent();
    tgs.append("double now = 0;");
    tgs.newLine();

    ROSSUtils.rossStructCheckpointInstantiation(deslModel, ctx);

    ROSSUtils.rossSwitchEvent(c, true, ctx);
    ctx.getBuffer().area().decreaseIndent();

    tgs.append("}");
    tgs.newLine();
    tgs.newLine();
  }
  public static void rossSwitchEvent(SNode c, boolean isForward, final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.indent();
    tgs.append("switch(content->event_type) {");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    for (SNode handler : Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getChildren(c, LINKS.handlers$Nr2P), CONCEPTS.ReversibleEventHandler$Ov))) {
      if (!(isForward) || (!(SPropertyOperations.getString(handler, PROPS.eventName$rI8o).equals("INIT")) && !(SPropertyOperations.getString(handler, PROPS.eventName$rI8o).equals("LP_INIT")))) {
        tgs.newLine();
        tgs.indent();
        tgs.append("case event_");
        tgs.append(SPropertyOperations.getString(handler, PROPS.eventName$rI8o));
        tgs.append(":");
        tgs.newLine();
        ctx.getBuffer().area().increaseIndent();
        if (isForward) {
          tgs.indent();
          tgs.appendNode(SLinkOperations.getTarget(SLinkOperations.getTarget(handler, LINKS.forwardFunction$5bPH), LINKS.revBody$QkEt));
        } else {
          tgs.indent();
          tgs.appendNode(SLinkOperations.getTarget(SLinkOperations.getTarget(handler, LINKS.reverseFunction$yyGT), LINKS.revBody$QkEt));
        }
        tgs.indent();
        tgs.append("break;");
        tgs.newLine();
        ctx.getBuffer().area().decreaseIndent();
      }
    }

    tgs.newLine();
    tgs.indent();
    tgs.append("default:");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("fprintf(stderr, \"Unknown event type! (event type = %d)\", content->event_type);");
    tgs.newLine();
    tgs.indent();
    tgs.append("abort();");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    ctx.getBuffer().area().decreaseIndent();
    tgs.indent();
    tgs.append("}");
    tgs.newLine();
  }
  public static void rossStructCheckpointInstantiation(SNode deslModel, final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.indent();
    tgs.append("struct checkpoint cp = {0};");
    tgs.newLine();
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty eventName$rI8o = MetaAdapterFactory.getProperty(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x549487e5d88a4291L, 0x113f0963d355264aL, "eventName");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink stateStruct$NqNO = MetaAdapterFactory.getContainmentLink(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x4117a694e5b8c1a0L, 0x4117a694e5b8c1a2L, "stateStruct");
    /*package*/ static final SContainmentLink messageStruct$xVlJ = MetaAdapterFactory.getContainmentLink(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x1ada9a09174c9630L, 0x6de6339fa564bed8L, "messageStruct");
    /*package*/ static final SContainmentLink forwardFunction$5bPH = MetaAdapterFactory.getContainmentLink(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x2dc3a690836fd0d0L, 0x74d88000543a2a9fL, "forwardFunction");
    /*package*/ static final SContainmentLink revBody$QkEt = MetaAdapterFactory.getContainmentLink(0x5eb14d5ab5f74626L, 0xa63b80c6b9db7397L, 0x5e81f50da12f055fL, 0x5e81f50da12f79a6L, "revBody");
    /*package*/ static final SContainmentLink reverseFunction$yyGT = MetaAdapterFactory.getContainmentLink(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x2dc3a690836fd0d0L, 0x5e81f50da138219aL, "reverseFunction");
    /*package*/ static final SContainmentLink handlers$Nr2P = MetaAdapterFactory.getContainmentLink(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x4117a694e5b8c1a0L, 0x4117a694e5b8c1a3L, "handlers");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ReversibleEventHandler$Ov = MetaAdapterFactory.getConcept(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x2dc3a690836fd0d0L, "DESL.structure.ReversibleEventHandler");
  }
}
