package ReversibleFunctions.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenAspectBase;
import ReversibleFunctions.structure.LanguageConceptSwitch;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.text.rt.TextGenDescriptor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.text.rt.TextGenModelOutline;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TextGenAspectDescriptor extends TextGenAspectBase {
  private final LanguageConceptSwitch myIndex = new LanguageConceptSwitch();

  public TextGenAspectDescriptor() {
  }

  @Nullable
  @Override
  public TextGenDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    switch (myIndex.index(concept)) {
      case LanguageConceptSwitch.ReversibleFunction:
        return new ReversibleFunction_TextGen();
      case LanguageConceptSwitch.ReversibleMacro:
        return new ReversibleMacro_TextGen();
      case LanguageConceptSwitch.ReversibleMacroArgument:
        return new ReversibleMacroArgument_TextGen();
      case LanguageConceptSwitch.ReversibleMacroArgumentRef:
        return new ReversibleMacroArgumentRef_TextGen();
      case LanguageConceptSwitch.ReversibleScriptExp:
        return new ReversibleScriptExp_TextGen();
    }
    return null;
  }

  @Override
  public void breakdownToUnits(@NotNull TextGenModelOutline outline) {
    for (SNode root : outline.getModel().getRootNodes()) {
      if (root.getConcept().equals(CONCEPTS.ReversibleScriptExp$Xn)) {
        String fname = getFileName_ReversibleScriptExp(root);
        String ext = getFileExtension_ReversibleScriptExp(root);
        outline.registerTextUnit((ext == null ? fname : (fname + '.' + ext)), root);
        continue;
      }
    }
  }
  private static String getFileName_ReversibleScriptExp(SNode node) {
    return "function";
  }
  private static String getFileExtension_ReversibleScriptExp(SNode node) {
    return null;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ReversibleScriptExp$Xn = MetaAdapterFactory.getConcept(0x5eb14d5ab5f74626L, 0xa63b80c6b9db7397L, 0x56ee1731ff842b7dL, "ReversibleFunctions.structure.ReversibleScriptExp");
  }
}
