package ReversibleFunctions.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int ReversibleFunction = 0;
  public static final int ReversibleScript = 1;
  public static final int ReversibleScriptExp = 2;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x5eb14d5ab5f74626L, 0xa63b80c6b9db7397L);
    builder.put(0x5e81f50da12f055fL, ReversibleFunction);
    builder.put(0x56ee1731fef0eae5L, ReversibleScript);
    builder.put(0x56ee1731ff842b7dL, ReversibleScriptExp);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
