package ReversibleStatements.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;

public class CommentedStatement_SubstituteMenu extends SubstituteMenuBase {
  public CommentedStatement_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for " + "CommentedStatement", new SNodePointer("r:ad0a2569-6d3a-499c-b8a8-ddd62346572e(ReversibleStatements.editor)", "2531002643696481125")));
  }

}
