package ReversibleExpressions.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.core.behavior.BaseConcept__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SConcept;

public final class BinaryExpression__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x7af69e2e83a1ba34L, "ReversibleExpressions.structure.BinaryExpression");

  public static final SMethod<Boolean> isLValue_id6iIoqg1yDKH = new SMethodBuilder<Boolean>(new SJavaCompoundTypeImpl(Boolean.TYPE)).name("isLValue").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(7254843406768839725L).languageId(0x9379c4f95eb496d4L, 0x9abffa92487542bfL).build2();
  public static final SMethod<Boolean> isStaticallyEvaluatable_id3ilck8Kr3zN = new SMethodBuilder<Boolean>(new SJavaCompoundTypeImpl(Boolean.TYPE)).name("isStaticallyEvaluatable").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(3788988821852141811L).languageId(0x9379c4f95eb496d4L, 0x9abffa92487542bfL).build2();
  public static final SMethod<String> renderReadable_id1VQvajLb13M = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("renderReadable").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(2231107713271337202L).languageId(0x9379c4f95eb496d4L, 0x9abffa92487542bfL).build2();
  public static final SMethod<Boolean> isSideeffectFree_id6SENleF$SRD = new SMethodBuilder<Boolean>(new SJavaCompoundTypeImpl(Boolean.TYPE)).name("isSideeffectFree").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(7938383052438474217L).languageId(0x9379c4f95eb496d4L, 0x9abffa92487542bfL).build2();
  public static final SMethod<Boolean> requiresParensAroundArgument_id3_qrK00j4rM = new SMethodBuilder<Boolean>(new SJavaCompoundTypeImpl(Boolean.TYPE)).name("requiresParensAroundArgument").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(4132737653861533426L).languageId(0x9379c4f95eb496d4L, 0x9abffa92487542bfL).build2(SMethodBuilder.createJavaParameter((Class<SNode>) ((Class) Object.class), ""));
  public static final SMethod<SNode> getSyntacticallyLeftSideExpression_id4e6KBjFhyzo = new SMethodBuilder<SNode>(new SJavaCompoundTypeImpl((Class<SNode>) ((Class) Object.class))).name("getSyntacticallyLeftSideExpression").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(4865790254839638232L).languageId(0x9379c4f95eb496d4L, 0x9abffa92487542bfL).build2();
  public static final SMethod<SNode> getSyntacticallyRightSideExpression_id4e6KBjFh$LK = new SMethodBuilder<SNode>(new SJavaCompoundTypeImpl((Class<SNode>) ((Class) Object.class))).name("getSyntacticallyRightSideExpression").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(4865790254839647344L).languageId(0x9379c4f95eb496d4L, 0x9abffa92487542bfL).build2();
  public static final SMethod<Void> setSyntacticallyLeftSideExpression_id4e6KBjFhBuf = new SMethodBuilder<Void>(new SJavaCompoundTypeImpl(Void.class)).name("setSyntacticallyLeftSideExpression").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(4865790254839658383L).languageId(0x9379c4f95eb496d4L, 0x9abffa92487542bfL).build2(SMethodBuilder.createJavaParameter((Class<SNode>) ((Class) Object.class), ""));
  public static final SMethod<Void> setSyntacticallyRightSideExpression_id4e6KBjFhDIu = new SMethodBuilder<Void>(new SJavaCompoundTypeImpl(Void.class)).name("setSyntacticallyRightSideExpression").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(4865790254839667614L).languageId(0x9379c4f95eb496d4L, 0x9abffa92487542bfL).build2(SMethodBuilder.createJavaParameter((Class<SNode>) ((Class) Object.class), ""));
  public static final SMethod<String> getPresentation_idhEwIMiw = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("getPresentation").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(1213877396640L).languageId(0x9b92103b95ca8c0cL, 0xceab519525ea4f22L).build2();
  public static final SMethod<Integer> getFontStyle_id6P3AdoeYlwX = new SMethodBuilder<Integer>(new SJavaCompoundTypeImpl(Integer.TYPE)).name("getFontStyle").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(7873304618715404349L).languageId(0x9379c4f95eb496d4L, 0x9abffa92487542bfL).build2();
  public static final SMethod<String> getReversedOperator_id4e6KBjCJeOF = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("getReversedOperator").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(4865790254797090091L).languageId(0x9379c4f95eb496d4L, 0x9abffa92487542bfL).build2();
  public static final SMethod<Boolean> isLoopCondition_id7FTvvGQ_l_a = new SMethodBuilder<Boolean>(new SJavaCompoundTypeImpl(Boolean.TYPE)).name("isLoopCondition").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(8861252259734182218L).languageId(0x9379c4f95eb496d4L, 0x9abffa92487542bfL).build2();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(isLValue_id6iIoqg1yDKH, isStaticallyEvaluatable_id3ilck8Kr3zN, renderReadable_id1VQvajLb13M, isSideeffectFree_id6SENleF$SRD, requiresParensAroundArgument_id3_qrK00j4rM, getSyntacticallyLeftSideExpression_id4e6KBjFhyzo, getSyntacticallyRightSideExpression_id4e6KBjFh$LK, setSyntacticallyLeftSideExpression_id4e6KBjFhBuf, setSyntacticallyRightSideExpression_id4e6KBjFhDIu, getPresentation_idhEwIMiw, getFontStyle_id6P3AdoeYlwX, getReversedOperator_id4e6KBjCJeOF, isLoopCondition_id7FTvvGQ_l_a);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static boolean isLValue_id6iIoqg1yDKH(@NotNull SNode __thisNode__) {
    return false;
  }
  /*package*/ static boolean isStaticallyEvaluatable_id3ilck8Kr3zN(@NotNull SNode __thisNode__) {
    return (boolean) ReversibleExpression__BehaviorDescriptor.isStaticallyEvaluatable_id3ilck8Kr3zN.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.left$KPKR)) && (boolean) ReversibleExpression__BehaviorDescriptor.isStaticallyEvaluatable_id3ilck8Kr3zN.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.right$KPZS));
  }
  /*package*/ static String renderReadable_id1VQvajLb13M(@NotNull SNode __thisNode__) {
    return ReversibleExpression__BehaviorDescriptor.renderReadable_id1VQvajLb13M.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.left$KPKR)) + " " + SConceptOperations.conceptAlias(SNodeOperations.getConcept(__thisNode__)) + " " + ReversibleExpression__BehaviorDescriptor.renderReadable_id1VQvajLb13M.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.right$KPZS));
  }
  /*package*/ static boolean isSideeffectFree_id6SENleF$SRD(@NotNull SNode __thisNode__) {
    return (boolean) ReversibleExpression__BehaviorDescriptor.isSideeffectFree_id6SENleF$SRD.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.left$KPKR)) && (boolean) ReversibleExpression__BehaviorDescriptor.isSideeffectFree_id6SENleF$SRD.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.right$KPZS));
  }
  /*package*/ static boolean requiresParensAroundArgument_id3_qrK00j4rM(@NotNull SNode __thisNode__, SNode argument) {
    return false;
  }
  /*package*/ static SNode getSyntacticallyLeftSideExpression_id4e6KBjFhyzo(@NotNull SNode __thisNode__) {
    return SLinkOperations.getTarget(__thisNode__, LINKS.left$KPKR);
  }
  /*package*/ static SNode getSyntacticallyRightSideExpression_id4e6KBjFh$LK(@NotNull SNode __thisNode__) {
    return SLinkOperations.getTarget(__thisNode__, LINKS.right$KPZS);
  }
  /*package*/ static void setSyntacticallyLeftSideExpression_id4e6KBjFhBuf(@NotNull SNode __thisNode__, SNode expression) {
    SLinkOperations.setTarget(__thisNode__, LINKS.left$KPKR, expression);
  }
  /*package*/ static void setSyntacticallyRightSideExpression_id4e6KBjFhDIu(@NotNull SNode __thisNode__, SNode expression) {
    SLinkOperations.setTarget(__thisNode__, LINKS.right$KPZS, expression);
  }
  /*package*/ static String getPresentation_idhEwIMiw(@NotNull SNode __thisNode__) {
    return BaseConcept__BehaviorDescriptor.getPresentation_idhEwIMiw.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.left$KPKR)) + " " + SConceptOperations.conceptAlias(SNodeOperations.getConcept(__thisNode__)) + " " + BaseConcept__BehaviorDescriptor.getPresentation_idhEwIMiw.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.right$KPZS));
  }
  /*package*/ static int getFontStyle_id6P3AdoeYlwX(@NotNull SNode __thisNode__) {
    return SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x1006551b180L, "jetbrains.mps.lang.editor.structure._FontStyle_Enum"), 0x1082a1c2aa1L, "PLAIN").getOrdinal() + 1;
  }
  /*package*/ static String getReversedOperator_id4e6KBjCJeOF(@NotNull SNode __thisNode__) {
    return "";
  }
  /*package*/ static boolean isLoopCondition_id7FTvvGQ_l_a(@NotNull SNode __thisNode__) {
    return SNodeOperations.hasRole(__thisNode__, LINKS.condition$3gCl) || SNodeOperations.hasRole(SNodeOperations.getParent(__thisNode__), LINKS.condition$3gCl) || Sequence.fromIterable(SNodeOperations.ofConcept(SNodeOperations.getNodeAncestors(__thisNode__, null, false), CONCEPTS.ReversibleExpression$Zd)).where((it) -> SNodeOperations.hasRole(it, LINKS.condition$3gCl)).isNotEmpty();

  }

  /*package*/ BinaryExpression__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((Boolean) isLValue_id6iIoqg1yDKH(node));
      case 1:
        return (T) ((Boolean) isStaticallyEvaluatable_id3ilck8Kr3zN(node));
      case 2:
        return (T) ((String) renderReadable_id1VQvajLb13M(node));
      case 3:
        return (T) ((Boolean) isSideeffectFree_id6SENleF$SRD(node));
      case 4:
        return (T) ((Boolean) requiresParensAroundArgument_id3_qrK00j4rM(node, (SNode) parameters[0]));
      case 5:
        return (T) ((SNode) getSyntacticallyLeftSideExpression_id4e6KBjFhyzo(node));
      case 6:
        return (T) ((SNode) getSyntacticallyRightSideExpression_id4e6KBjFh$LK(node));
      case 7:
        setSyntacticallyLeftSideExpression_id4e6KBjFhBuf(node, (SNode) parameters[0]);
        return null;
      case 8:
        setSyntacticallyRightSideExpression_id4e6KBjFhDIu(node, (SNode) parameters[0]);
        return null;
      case 9:
        return (T) ((String) getPresentation_idhEwIMiw(node));
      case 10:
        return (T) ((Integer) getFontStyle_id6P3AdoeYlwX(node));
      case 11:
        return (T) ((String) getReversedOperator_id4e6KBjCJeOF(node));
      case 12:
        return (T) ((Boolean) isLoopCondition_id7FTvvGQ_l_a(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink right$KPZS = MetaAdapterFactory.getContainmentLink(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x7af69e2e83a1ba34L, 0x7af69e2e83a1ba41L, "right");
    /*package*/ static final SContainmentLink left$KPKR = MetaAdapterFactory.getContainmentLink(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x7af69e2e83a1ba34L, 0x7af69e2e83a1ba40L, "left");
    /*package*/ static final SContainmentLink condition$3gCl = MetaAdapterFactory.getContainmentLink(0xf75f9e3fb00b4997L, 0x8af20a8ce6b25221L, 0x6337a44ca461bdf4L, 0x64ae61a401870e43L, "condition");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ReversibleExpression$Zd = MetaAdapterFactory.getConcept(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x7af69e2e83a1ba32L, "ReversibleExpressions.structure.ReversibleExpression");
  }
}
