package ReversibleExpressions.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SProperty;

public final class ReversibleFunctionCall__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x2e6ecb766f1587b4L, "ReversibleExpressions.structure.ReversibleFunctionCall");

  public static final SMethod<SNode> getFunction_id2TIMRpJnWr_ = new SMethodBuilder<SNode>(new SJavaCompoundTypeImpl((Class<SNode>) ((Class) Object.class))).name("getFunction").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(3345835282717984485L).languageId(0x9379c4f95eb496d4L, 0x9abffa92487542bfL).build2();
  public static final SMethod<List<SNode>> getFormals_id2TIMRpJob12 = new SMethodBuilder<List<SNode>>(new SJavaCompoundTypeImpl((Class<List<SNode>>) ((Class) Object.class))).name("getFormals").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(3345835282718044226L).languageId(0x9379c4f95eb496d4L, 0x9abffa92487542bfL).build2();
  public static final SMethod<List<SNode>> getActuals_id2TIMRpJodKn = new SMethodBuilder<List<SNode>>(new SJavaCompoundTypeImpl((Class<List<SNode>>) ((Class) Object.class))).name("getActuals").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(3345835282718055447L).languageId(0x9379c4f95eb496d4L, 0x9abffa92487542bfL).build2();
  public static final SMethod<Boolean> hasEllipsis_id2TIMRpJok1r = new SMethodBuilder<Boolean>(new SJavaCompoundTypeImpl(Boolean.TYPE)).name("hasEllipsis").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(3345835282718081115L).languageId(0x9379c4f95eb496d4L, 0x9abffa92487542bfL).build2();
  public static final SMethod<SNode> getReturnType_id2TIMRpJoBIg = new SMethodBuilder<SNode>(new SJavaCompoundTypeImpl((Class<SNode>) ((Class) Object.class))).name("getReturnType").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(3345835282718161808L).languageId(0x9379c4f95eb496d4L, 0x9abffa92487542bfL).build2();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(getFunction_id2TIMRpJnWr_, getFormals_id2TIMRpJob12, getActuals_id2TIMRpJodKn, hasEllipsis_id2TIMRpJok1r, getReturnType_id2TIMRpJoBIg);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static SNode getFunction_id2TIMRpJnWr_(@NotNull SNode __thisNode__) {
    return SLinkOperations.getTarget(__thisNode__, LINKS.function$EyYZ);
  }
  /*package*/ static List<SNode> getFormals_id2TIMRpJob12(@NotNull SNode __thisNode__) {
    return SLinkOperations.getChildren(SLinkOperations.getTarget(__thisNode__, LINKS.function$EyYZ), LINKS.arguments$gPkY);
  }
  /*package*/ static List<SNode> getActuals_id2TIMRpJodKn(@NotNull SNode __thisNode__) {
    return SLinkOperations.getChildren(__thisNode__, LINKS.actuals$EywX);
  }
  /*package*/ static boolean hasEllipsis_id2TIMRpJok1r(@NotNull SNode __thisNode__) {
    return SPropertyOperations.getBoolean(SLinkOperations.getTarget(__thisNode__, LINKS.function$EyYZ), PROPS.hasEllipsis$NQI);
  }
  /*package*/ static SNode getReturnType_id2TIMRpJoBIg(@NotNull SNode __thisNode__) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(__thisNode__, LINKS.function$EyYZ), LINKS.type$m1NA);
  }

  /*package*/ ReversibleFunctionCall__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((SNode) getFunction_id2TIMRpJnWr_(node));
      case 1:
        return (T) ((List<SNode>) getFormals_id2TIMRpJob12(node));
      case 2:
        return (T) ((List<SNode>) getActuals_id2TIMRpJodKn(node));
      case 3:
        return (T) ((Boolean) hasEllipsis_id2TIMRpJok1r(node));
      case 4:
        return (T) ((SNode) getReturnType_id2TIMRpJoBIg(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink function$EyYZ = MetaAdapterFactory.getReferenceLink(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x2e6ecb766f1587b4L, 0x2e6ecb766f15bfbaL, "function");
    /*package*/ static final SContainmentLink arguments$gPkY = MetaAdapterFactory.getContainmentLink(0x5eb14d5ab5f74626L, 0xa63b80c6b9db7397L, 0x5e81f50da12f055fL, 0x4f39f90935e92f45L, "arguments");
    /*package*/ static final SContainmentLink actuals$EywX = MetaAdapterFactory.getContainmentLink(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x2e6ecb766f1587b4L, 0x2e6ecb766f15bfb8L, "actuals");
    /*package*/ static final SContainmentLink type$m1NA = MetaAdapterFactory.getContainmentLink(0x5eb14d5ab5f74626L, 0xa63b80c6b9db7397L, 0x5e81f50da12f055fL, 0x4b1eecbba6894aa4L, "type");
  }

  private static final class PROPS {
    /*package*/ static final SProperty hasEllipsis$NQI = MetaAdapterFactory.getProperty(0x5eb14d5ab5f74626L, 0xa63b80c6b9db7397L, 0x5e81f50da12f055fL, 0x4b1eecbba689652fL, "hasEllipsis");
  }
}
