package DESL.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class IHandler_Constraints extends BaseConstraintsDescriptor {
  /*package*/ IHandler_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.IHandler$Jq, initContext);
  }

  private static final class CONCEPTS {
    /*package*/ static final SInterfaceConcept IHandler$Jq = MetaAdapterFactory.getInterfaceConcept(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x549487e5d88a4291L, "DESL.structure.IHandler");
  }
}
