package DESL.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SProperty;

public class InitTopology_Constraints extends BaseConstraintsDescriptor {
  /*package*/ InitTopology_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.InitTopology$gx, initContext);
    record(new RD1(this));
  }

  /*package*/ static final class RD1 extends BaseReferenceConstraintsDescriptor {
    /*package*/ RD1(ConstraintsDescriptor container) {
      super(LINKS.variable$t3Yu, container, false, true);
    }
    @Override
    public boolean validate(final SNode referenceNode, final SNode oldReferentNode, final SNode newReferentNode) {
      return true;
    }
    @Override
    public void onReferenceSet(final SNode referenceNode, final SNode oldReferentNode, final SNode newReferentNode) {
      SLinkOperations.setTarget(referenceNode, LINKS.variable$t3Yu, newReferentNode);
      SPropertyOperations.assign(referenceNode, PROPS.variableName$Fc4X, SPropertyOperations.getString(newReferentNode, PROPS.name$MnvL));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept InitTopology$gx = MetaAdapterFactory.getConcept(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x1a36c02200c1a246L, "DESL.structure.InitTopology");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink variable$t3Yu = MetaAdapterFactory.getReferenceLink(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x1a36c02200c1a246L, 0x1a36c02200c1a247L, "variable");
  }

  private static final class PROPS {
    /*package*/ static final SProperty variableName$Fc4X = MetaAdapterFactory.getProperty(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x1a36c02200c1a246L, 0x1a36c022010762d7L, "variableName");
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }
}
