package ReversibleExpressions.listeners;

/*Generated by MPS */

import com.mbeddr.mpsutil.modellisteners.runtime.IModelListenersDescriptor;
import com.mbeddr.mpsutil.modellisteners.runtime.IModelListener;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import com.mbeddr.mpsutil.modellisteners.runtime.ChildListener;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class ModelListenersDescriptor implements IModelListenersDescriptor {
  public ModelListenersDescriptor() {
  }

  public Iterable<IModelListener> getListeners() {
    List<IModelListener> listeners = ListSequence.fromList(new ArrayList<IModelListener>());

    ListSequence.fromList(listeners).addElement(new ChildListener(CONCEPTS.AssignmentExpr$aj, LINKS.left$KPKR) {
      @Override
      public void childAdded(final SNode instance, final SNode child) {
        SNode type = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x7af69e2e83a1ba36L, "com.mbeddr.core.expressions.structure.Type"));
        {
          final SNode lvr = child;
          if (SNodeOperations.isInstanceOf(lvr, CONCEPTS.LocalVarRef$O3)) {
            type = SNodeOperations.copyNode(SLinkOperations.getTarget(SLinkOperations.getTarget(lvr, LINKS.var$uDqP), LINKS.type$sXU3));
          }
        }
        {
          final SNode ar = child;
          if (SNodeOperations.isInstanceOf(ar, CONCEPTS.ArgumentRef$Ar)) {
            type = SNodeOperations.copyNode(SLinkOperations.getTarget(SLinkOperations.getTarget(ar, LINKS.arg$bO7D), LINKS.type$sXU3));
          }
        }

        SLinkOperations.setTarget(SLinkOperations.getTarget(instance, LINKS.variable$WrxR), LINKS.type$sXU3, type);
        SLinkOperations.setTarget(SLinkOperations.getTarget(instance, LINKS.variable$WrxR), LINKS.init$41s$, SNodeOperations.copyNode(child));
      }
    });
    ListSequence.fromList(listeners).addElement(new ChildListener(CONCEPTS.DirectModuloAssignmentExpression$5b, LINKS.left$KPKR) {
      @Override
      public void childAdded(final SNode instance, final SNode child) {
        SNode type = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x7af69e2e83a1ba36L, "com.mbeddr.core.expressions.structure.Type"));
        {
          final SNode lvr = child;
          if (SNodeOperations.isInstanceOf(lvr, CONCEPTS.LocalVarRef$O3)) {
            type = SNodeOperations.copyNode(SLinkOperations.getTarget(SLinkOperations.getTarget(lvr, LINKS.var$uDqP), LINKS.type$sXU3));
          }
        }
        {
          final SNode ar = child;
          if (SNodeOperations.isInstanceOf(ar, CONCEPTS.ArgumentRef$Ar)) {
            type = SNodeOperations.copyNode(SLinkOperations.getTarget(SLinkOperations.getTarget(ar, LINKS.arg$bO7D), LINKS.type$sXU3));
          }
        }

        SLinkOperations.setTarget(SLinkOperations.getTarget(instance, LINKS.variable$WrxR), LINKS.type$sXU3, type);
        SLinkOperations.setTarget(SLinkOperations.getTarget(instance, LINKS.variable$WrxR), LINKS.init$41s$, SNodeOperations.copyNode(child));
      }
    });

    return listeners;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept AssignmentExpr$aj = MetaAdapterFactory.getConcept(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x4e85add925440dL, "ReversibleExpressions.structure.AssignmentExpr");
    /*package*/ static final SConcept LocalVarRef$O3 = MetaAdapterFactory.getConcept(0xf75f9e3fb00b4997L, 0x8af20a8ce6b25221L, 0x1d0c3765e2e1d67aL, "ReversibleStatements.structure.LocalVarRef");
    /*package*/ static final SConcept ArgumentRef$Ar = MetaAdapterFactory.getConcept(0xf75f9e3fb00b4997L, 0x8af20a8ce6b25221L, 0x586abb2d564e82ffL, "ReversibleStatements.structure.ArgumentRef");
    /*package*/ static final SConcept DirectModuloAssignmentExpression$5b = MetaAdapterFactory.getConcept(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x63d2f6d2334415d3L, "ReversibleExpressions.structure.DirectModuloAssignmentExpression");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink left$KPKR = MetaAdapterFactory.getContainmentLink(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x7af69e2e83a1ba34L, 0x7af69e2e83a1ba40L, "left");
    /*package*/ static final SReferenceLink var$uDqP = MetaAdapterFactory.getReferenceLink(0xf75f9e3fb00b4997L, 0x8af20a8ce6b25221L, 0x1d0c3765e2e1d67aL, 0x1d0c3765e2e1fe27L, "var");
    /*package*/ static final SContainmentLink type$sXU3 = MetaAdapterFactory.getContainmentLink(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x46a2a92ac61b183L, 0x46a2a92ac61b184L, "type");
    /*package*/ static final SReferenceLink arg$bO7D = MetaAdapterFactory.getReferenceLink(0xf75f9e3fb00b4997L, 0x8af20a8ce6b25221L, 0x586abb2d564e82ffL, 0x586abb2d564e8301L, "arg");
    /*package*/ static final SContainmentLink variable$WrxR = MetaAdapterFactory.getContainmentLink(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x586abb2d5743cb68L, 0x586abb2d5743cb69L, "variable");
    /*package*/ static final SContainmentLink init$41s$ = MetaAdapterFactory.getContainmentLink(0xf75f9e3fb00b4997L, 0x8af20a8ce6b25221L, 0x3a16e3a9c7ad96e6L, 0x3a16e3a9c7ae01f7L, "init");
  }
}
