package ReversibleExpressions.plugin;

/*Generated by MPS */

import jetbrains.mps.smodel.structure.DefaultExtensionDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.structure.ExtensionPoint;

public class ExtensionDescriptor extends DefaultExtensionDescriptor {
  public ExtensionDescriptor() {
    super(Arrays.asList(new ExtensionPoint("ReversibleExpressions.PrintfFormatCustomizer"), new ExtensionPoint("ReversibleExpressions.PrintfFunctionCustomizer")), null);
  }
}
