package ReversibleExpressions.typesystem;

/*Generated by MPS */

import jetbrains.mps.errors.QuickFix_Runtime;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class addMissingMinAndMaxValues_QuickFix extends QuickFix_Runtime {
  public addMissingMinAndMaxValues_QuickFix() {
    super(new SNodePointer("r:a08f1c59-09f4-4839-91dc-89de02b086a5(ReversibleExpressions.typesystem)", "6658270785808285221"));
  }
  public void execute(SNode node) {
    SNode sn = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x172ddc48ec9eb7ceL, "ReversibleExpressions.structure.ScientificNumber"));
    SPropertyOperations.assign(sn, PROPS.prefix$Su1m, "-1");
    SPropertyOperations.assign(sn, PROPS.postfix$Suvo, "37");
    SLinkOperations.setTarget(((SNode) addMissingMinAndMaxValues_QuickFix.this.getField("tsc")[0]), LINKS.minFloatValue$OwpR, SNodeOperations.copyNode(sn));
    SLinkOperations.setTarget(((SNode) addMissingMinAndMaxValues_QuickFix.this.getField("tsc")[0]), LINKS.minDoubleValue$ODMv, SNodeOperations.copyNode(sn));

    SPropertyOperations.assign(sn, PROPS.prefix$Su1m, "1");
    SLinkOperations.setTarget(((SNode) addMissingMinAndMaxValues_QuickFix.this.getField("tsc")[0]), LINKS.maxFloatValue$DQPu, SNodeOperations.copyNode(sn));
    SLinkOperations.setTarget(((SNode) addMissingMinAndMaxValues_QuickFix.this.getField("tsc")[0]), LINKS.maxDoubleValue$Oyx0, SNodeOperations.copyNode(sn));

  }

  private static final class PROPS {
    /*package*/ static final SProperty prefix$Su1m = MetaAdapterFactory.getProperty(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x172ddc48ec9eb7ceL, 0x172ddc48ec9ebd59L, "prefix");
    /*package*/ static final SProperty postfix$Suvo = MetaAdapterFactory.getProperty(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x172ddc48ec9eb7ceL, 0x172ddc48ec9ebd5bL, "postfix");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink minFloatValue$OwpR = MetaAdapterFactory.getContainmentLink(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x2e4bd40f1cbdfd34L, 0x5c66ee00ad4d945aL, "minFloatValue");
    /*package*/ static final SContainmentLink minDoubleValue$ODMv = MetaAdapterFactory.getContainmentLink(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x2e4bd40f1cbdfd34L, 0x5c66ee00ad4d946dL, "minDoubleValue");
    /*package*/ static final SContainmentLink maxFloatValue$DQPu = MetaAdapterFactory.getContainmentLink(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x2e4bd40f1cbdfd34L, 0x5c66ee00ad4d932dL, "maxFloatValue");
    /*package*/ static final SContainmentLink maxDoubleValue$Oyx0 = MetaAdapterFactory.getContainmentLink(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x2e4bd40f1cbdfd34L, 0x5c66ee00ad4d9463L, "maxDoubleValue");
  }
}
