package ReversibleExpressions.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import ReversibleExpressions.behavior.ReversibleExpression__BehaviorDescriptor;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.typechecking.TypecheckingFacade;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;

public class check_UnaryPrePosModificationExpression_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_UnaryPrePosModificationExpression_NonTypesystemRule() {
  }
  public void applyRule(final SNode unaryPrePosModificationExpression, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    final SNode exp = SLinkOperations.getTarget(unaryPrePosModificationExpression, LINKS.expression$HKAI);
    if ((exp != null) && !((boolean) ReversibleExpression__BehaviorDescriptor.isLValue_id6iIoqg1yDKH.invoke(exp))) {
      {
        final MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(exp, "not an lvalue", "r:a08f1c59-09f4-4839-91dc-89de02b086a5(ReversibleExpressions.typesystem)", "6755428438087233160", null, errorTarget);
      }
    }
    if (SNodeOperations.isInstanceOf(TypecheckingFacade.getFromContext().getTypeOf(exp), CONCEPTS.PrimitiveType$eN) && !(SNodeOperations.isInstanceOf(TypecheckingFacade.getFromContext().getTypeOf(exp), CONCEPTS.INumeric$Bt))) {
      {
        final MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(exp, "not a numeric type", "r:a08f1c59-09f4-4839-91dc-89de02b086a5(ReversibleExpressions.typesystem)", "4813231556416939976", null, errorTarget);
      }
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.UnaryPrePosModificationExpression$3r;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink expression$HKAI = MetaAdapterFactory.getContainmentLink(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x29b5b7c4a3763232L, 0x64ae61a4018a9c50L, "expression");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept PrimitiveType$eN = MetaAdapterFactory.getConcept(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x7af69e2e83a1ba38L, "com.mbeddr.core.expressions.structure.PrimitiveType");
    /*package*/ static final SInterfaceConcept INumeric$Bt = MetaAdapterFactory.getInterfaceConcept(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x379915b561cc59aaL, "com.mbeddr.core.expressions.structure.INumeric");
    /*package*/ static final SConcept UnaryPrePosModificationExpression$3r = MetaAdapterFactory.getConcept(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x632cdd5acfb8529eL, "ReversibleExpressions.structure.UnaryPrePosModificationExpression");
  }
}
