package ReversibleExpressions.typesystem;

/*Generated by MPS */

import jetbrains.mps.errors.QuickFix_Runtime;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;

public class convertCharToSignedChar_QuickFix extends QuickFix_Runtime {
  public convertCharToSignedChar_QuickFix() {
    super(new SNodePointer("r:a08f1c59-09f4-4839-91dc-89de02b086a5(ReversibleExpressions.typesystem)", "3390250080488381930"));
  }
  public String getDescription(SNode node) {
    return "Convert to signed char";
  }
  public void execute(SNode node) {
    SNodeOperations.replaceWithNewChild(SLinkOperations.getTarget(((SNode) convertCharToSignedChar_QuickFix.this.getField("tss")[0]), LINKS.basicType$_$2i), CONCEPTS.SignedCharType$k2);
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink basicType$_$2i = MetaAdapterFactory.getContainmentLink(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x2e4bd40f1cbdfd35L, 0x6809bf452de068caL, "basicType");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept SignedCharType$k2 = MetaAdapterFactory.getConcept(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x2f0c967c625d21abL, "com.mbeddr.core.expressions.structure.SignedCharType");
  }
}
