package ReversibleExpressions.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import ReversibleExpressions.behavior.ITypeDecorator__BehaviorDescriptor;
import com.mbeddr.core.expressions.behavior.IUnsigned__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.typesystem.inference.EquationInfo;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SProperty;

public class typeof_UnaryMinusExpression_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_UnaryMinusExpression_InferenceRule() {
  }
  public void applyRule(final SNode unaryMinusExpression, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    {
      final SNode exprType = typeCheckingContext.typeOf(SLinkOperations.getTarget(unaryMinusExpression, LINKS.expression$HKAI), "r:a08f1c59-09f4-4839-91dc-89de02b086a5(ReversibleExpressions.typesystem)", "7146330090837623499", true);
      typeCheckingContext.whenConcrete(exprType, () -> {
        SNode resultType;

        SNode valueType;

        if (SNodeOperations.isInstanceOf(typeCheckingContext.getExpandedNode(exprType), CONCEPTS.ITypeDecorator$WP)) {
          valueType = ITypeDecorator__BehaviorDescriptor.realValueType_id6cGRlFg4oMy.invoke(SNodeOperations.cast(typeCheckingContext.getExpandedNode(exprType), CONCEPTS.ITypeDecorator$WP));
        } else if (SNodeOperations.isInstanceOf(typeCheckingContext.getExpandedNode(exprType), CONCEPTS.PC99MeetType$$K)) {
          valueType = MeetTypeHelper.getConcreteType(SNodeOperations.cast(typeCheckingContext.getExpandedNode(exprType), CONCEPTS.IType$a9));
        } else {
          valueType = SNodeOperations.cast(typeCheckingContext.getExpandedNode(exprType), CONCEPTS.IType$a9);
        }
        if (SNodeOperations.isInstanceOf(valueType, CONCEPTS.IUnsigned$5A)) {
          SNode unsignedType = SNodeOperations.cast(valueType, CONCEPTS.IUnsigned$5A);
          valueType = IUnsigned__BehaviorDescriptor.createNextBiggerSignedCompanion_id6cGRlFg47bM.invoke(unsignedType);
          SPropertyOperations.assign(SNodeOperations.cast(valueType, CONCEPTS.Type$dP), PROPS.const$VWr7, SPropertyOperations.getBoolean(SNodeOperations.cast(unsignedType, CONCEPTS.Type$dP), PROPS.const$VWr7));
          SPropertyOperations.assign(SNodeOperations.cast(valueType, CONCEPTS.Type$dP), PROPS.volatile$hJNe, SPropertyOperations.getBoolean(SNodeOperations.cast(unsignedType, CONCEPTS.Type$dP), PROPS.volatile$hJNe));
        }

        if (SNodeOperations.isInstanceOf(typeCheckingContext.getExpandedNode(exprType), CONCEPTS.ITypeDecorator$WP)) {
          SNode copiedTD = SNodeOperations.cast(SNodeOperations.copyNode(typeCheckingContext.getExpandedNode(exprType)), CONCEPTS.ITypeDecorator$WP);
          ITypeDecorator__BehaviorDescriptor.setRealValueType_id6cGRlFg4$3O.invoke(copiedTD, valueType);
          resultType = SNodeOperations.cast(copiedTD, CONCEPTS.IType$a9);
        } else {
          resultType = valueType;
        }
        {
          SNode _nodeToCheck_1029348928467 = unaryMinusExpression;
          EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:a08f1c59-09f4-4839-91dc-89de02b086a5(ReversibleExpressions.typesystem)", "7146330090837701657", 0, null);
          typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:a08f1c59-09f4-4839-91dc-89de02b086a5(ReversibleExpressions.typesystem)", "7146330090837700264", true), (SNode) resultType, _info_12389875345);
        }
      }, "r:a08f1c59-09f4-4839-91dc-89de02b086a5(ReversibleExpressions.typesystem)", "7146330090837623347", false, false);
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.UnaryMinusExpression$d6;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return true;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink expression$HKAI = MetaAdapterFactory.getContainmentLink(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x29b5b7c4a3763232L, 0x64ae61a4018a9c50L, "expression");
  }

  private static final class CONCEPTS {
    /*package*/ static final SInterfaceConcept IType$a9 = MetaAdapterFactory.getInterfaceConcept(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x11f8a0774f2L, "jetbrains.mps.lang.core.structure.IType");
    /*package*/ static final SConcept PC99MeetType$$K = MetaAdapterFactory.getConcept(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x34ab7f1366694273L, "com.mbeddr.core.expressions.structure.PC99MeetType");
    /*package*/ static final SInterfaceConcept ITypeDecorator$WP = MetaAdapterFactory.getInterfaceConcept(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0xa526fcd7806eb53L, "ReversibleExpressions.structure.ITypeDecorator");
    /*package*/ static final SInterfaceConcept IUnsigned$5A = MetaAdapterFactory.getInterfaceConcept(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x61f402d2a8753377L, "com.mbeddr.core.expressions.structure.IUnsigned");
    /*package*/ static final SConcept Type$dP = MetaAdapterFactory.getConcept(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x7af69e2e83a1ba36L, "com.mbeddr.core.expressions.structure.Type");
    /*package*/ static final SConcept UnaryMinusExpression$d6 = MetaAdapterFactory.getConcept(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x373071ae5c652ee2L, "ReversibleExpressions.structure.UnaryMinusExpression");
  }

  private static final class PROPS {
    /*package*/ static final SProperty const$VWr7 = MetaAdapterFactory.getProperty(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x7af69e2e83a1ba36L, 0x28d183d9a4cc7da8L, "const");
    /*package*/ static final SProperty volatile$hJNe = MetaAdapterFactory.getProperty(0x61c69711ed614850L, 0x81d97714ff227fb0L, 0x7af69e2e83a1ba36L, 0x28d183d9a4fae02fL, "volatile");
  }
}
