package SimpleDES.editor;

/*Generated by MPS */

import javax.swing.JComponent;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import javax.swing.JButton;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.editor.runtime.selection.SelectionUtil;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.awt.Font;
import jetbrains.mps.nodeEditor.EditorSettings;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SConcept;

public class ButtonFactory {

  public static JComponent createNextFunction(final EditorContext editorContext, final SNode node) {
    JButton button = ButtonFactory.createButton(node, editorContext, "Create Function", new Runnable() {
      @Override
      public void run() {
        SNode function = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x6f36cc77d0c6228bL, "SimpleDES.structure.ExternalFunction"));
        SNodeOperations.insertNextSiblingChild(node, SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x6f36cc77d0c6228bL, "SimpleDES.structure.ExternalFunction")));
        SelectionUtil.selectNode(editorContext, function);
      }
    });
    return button;
  }

  public static JComponent createStruct(final EditorContext editorContext, final SNode node) {
    JButton button = ButtonFactory.createButton(node, editorContext, "Create Struct", new Runnable() {
      @Override
      public void run() {
        SNode struct = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x5808433cc497c577L, "SimpleDES.structure.StructDefinition"));
        SLinkOperations.setTarget(struct, LINKS.struct$10Oz, SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xefda956e491e4f00L, 0xba1436af2f213ecfL, 0x58bef62304fc0a2fL, "com.mbeddr.core.udt.structure.StructDeclaration")));
        SNodeOperations.insertNextSiblingChild(node, struct);
        SelectionUtil.selectNode(editorContext, struct);
      }
    });
    return button;
  }

  public static JComponent createExternalStruct(final EditorContext editorContext, final SNode node) {
    JButton button = ButtonFactory.createButton(node, editorContext, "Create External Struct", new Runnable() {
      @Override
      public void run() {
        SNode struct = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x5808433cc497c579L, "SimpleDES.structure.ExternalStructDefinition"));
        SNodeOperations.insertNextSiblingChild(node, struct);
        SelectionUtil.selectNode(editorContext, struct);
      }
    });
    return button;
  }

  public static JComponent createNextFunctionPrototype(final EditorContext editorContext, final SNode node) {
    JButton button = ButtonFactory.createButton(node, editorContext, "Create Function Prototype", new Runnable() {
      @Override
      public void run() {
        SNode function = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x6f36cc77d0c6228cL, "SimpleDES.structure.ExternalFunctionPrototype"));
        SNodeOperations.insertNextSiblingChild(node, function);
        SelectionUtil.selectNode(editorContext, function);
      }
    });
    return button;
  }

  public static JComponent createNextEvent(final EditorContext editorContext, final SNode node) {
    JButton button = ButtonFactory.createButton(node, editorContext, "Create Event", new Runnable() {
      @Override
      public void run() {
        SNode event = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x2e66f9a613f69c80L, "SimpleDES.structure.EventDefinition"));
        SLinkOperations.setTarget(event, LINKS.eventType$MGmZ, SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x7c2c5977e3e10df9L, "SimpleDES.structure.EventType")));
        ListSequence.fromList(SLinkOperations.getChildren(SNodeOperations.cast(node, CONCEPTS.DESModel$DK), LINKS.events$uflG)).addElement(event);
        SelectionUtil.selectNode(editorContext, event);
      }
    });
    return button;
  }


  public static JComponent addDocumentation(final EditorContext editorContext, final SNode node) {
    JButton button = ButtonFactory.createButton(node, editorContext, "Add Documentation", new Runnable() {
      @Override
      public void run() {
        {
          final SNode function = node;
          if (SNodeOperations.isInstanceOf(function, CONCEPTS.ExternalFunction$U_)) {
            SLinkOperations.setTarget(function, LINKS.docs$95P3, SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x6579f899e5d7c058L, "SimpleDES.structure.FunctionDocs")));
            SLinkOperations.setTarget(SLinkOperations.getTarget(function, LINKS.docs$95P3), LINKS.function$KLga, function);
            for (SNode parameter : ListSequence.fromList(SLinkOperations.getChildren(function, LINKS.arguments$6da0))) {
              SNode parameterDoc = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x6579f899e5d7c060L, "SimpleDES.structure.ParameterDocs"));
              SLinkOperations.setTarget(parameterDoc, LINKS.parameter$d8oD, SNodeOperations.as(parameter, CONCEPTS.Argument$9m));
              ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(function, LINKS.docs$95P3), LINKS.parametersDescription$HNUz)).addElement(parameterDoc);
              SelectionUtil.selectNode(editorContext, SLinkOperations.getTarget(function, LINKS.docs$95P3));
            }
          }
        }
        {
          final SNode handler = node;
          if (SNodeOperations.isInstanceOf(handler, CONCEPTS.EventHandler$Ov)) {
            SLinkOperations.setTarget(handler, LINKS.docs$5cjJ, SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x74d88000542f2672L, "SimpleDES.structure.EventHandlerDocs")));
            SLinkOperations.setTarget(SLinkOperations.getTarget(handler, LINKS.docs$5cjJ), LINKS.handler$I7Vk, handler);
            SelectionUtil.selectNode(editorContext, SLinkOperations.getTarget(handler, LINKS.docs$5cjJ));
          }
        }
        {
          final SNode eventDefinition = node;
          if (SNodeOperations.isInstanceOf(eventDefinition, CONCEPTS.EventDefinition$wO)) {
            SLinkOperations.setTarget(eventDefinition, LINKS.docs$MHy4, SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x2e66f9a613f69c83L, "SimpleDES.structure.EventDocs")));
            SLinkOperations.setTarget(SLinkOperations.getTarget(eventDefinition, LINKS.docs$MHy4), LINKS.event$PJOt, SLinkOperations.getTarget(eventDefinition, LINKS.eventType$MGmZ));
            SelectionUtil.selectNode(editorContext, SLinkOperations.getTarget(eventDefinition, LINKS.docs$MHy4));
          }
        }
      }
    });
    return button;
  }


  public static JComponent removeDocumentation(final EditorContext editorContext, final SNode node) {
    JButton button = ButtonFactory.createButton(node, editorContext, "Remove Documentation", new Runnable() {
      @Override
      public void run() {
        {
          final SNode function = node;
          if (SNodeOperations.isInstanceOf(function, CONCEPTS.ExternalFunction$U_)) {
            SLinkOperations.setTarget(function, LINKS.docs$95P3, null);
            SelectionUtil.selectNode(editorContext, function);
          }
        }
        {
          final SNode handler = node;
          if (SNodeOperations.isInstanceOf(handler, CONCEPTS.EventHandler$Ov)) {
            SLinkOperations.setTarget(handler, LINKS.docs$5cjJ, null);
            SelectionUtil.selectNode(editorContext, handler);
          }
        }
        {
          final SNode eventDefinition = node;
          if (SNodeOperations.isInstanceOf(eventDefinition, CONCEPTS.EventDefinition$wO)) {
            SLinkOperations.setTarget(eventDefinition, LINKS.docs$MHy4, null);
            SelectionUtil.selectNode(editorContext, eventDefinition);
          }
        }
      }
    });
    return button;
  }


  private static JButton createButton(final SNode node, final EditorContext editorContext, String title, final Runnable action) {
    JButton button = new JButton(title);
    button.setFont(new Font(EditorSettings.getInstance().getFontFamily(), Font.PLAIN, EditorSettings.getInstance().getFontSize() / 5 * 6));
    button.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent p0) {
        editorContext.getRepository().getModelAccess().executeCommandInEDT(action);
      }
    });
    return button;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink struct$10Oz = MetaAdapterFactory.getContainmentLink(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x5808433cc497c577L, 0x5808433cc497c57dL, "struct");
    /*package*/ static final SContainmentLink eventType$MGmZ = MetaAdapterFactory.getContainmentLink(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x2e66f9a613f69c80L, 0x2e66f9a613f69c82L, "eventType");
    /*package*/ static final SContainmentLink events$uflG = MetaAdapterFactory.getContainmentLink(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x1ada9a09174c9630L, 0x2dc3a69083753b9fL, "events");
    /*package*/ static final SContainmentLink docs$95P3 = MetaAdapterFactory.getContainmentLink(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x6f36cc77d0c6228bL, 0x6579f899e5d902d7L, "docs");
    /*package*/ static final SReferenceLink function$KLga = MetaAdapterFactory.getReferenceLink(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x6579f899e5d7c058L, 0x6579f899e5d7c091L, "function");
    /*package*/ static final SReferenceLink parameter$d8oD = MetaAdapterFactory.getReferenceLink(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x6579f899e5d7c060L, 0x6579f899e5f274c0L, "parameter");
    /*package*/ static final SContainmentLink parametersDescription$HNUz = MetaAdapterFactory.getContainmentLink(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x6579f899e5d7c058L, 0x6579f899e5d7c05eL, "parametersDescription");
    /*package*/ static final SContainmentLink arguments$6da0 = MetaAdapterFactory.getContainmentLink(0x6d11763d483d4b2bL, 0x8efc09336c1b0001L, 0x707ac195dd5d51f2L, 0x4f39f90935e92f45L, "arguments");
    /*package*/ static final SContainmentLink docs$5cjJ = MetaAdapterFactory.getContainmentLink(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x2dc3a690836fd0d0L, 0x74d88000543a2aa1L, "docs");
    /*package*/ static final SReferenceLink handler$I7Vk = MetaAdapterFactory.getReferenceLink(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x74d88000542f2672L, 0x74d88000542f2674L, "handler");
    /*package*/ static final SContainmentLink docs$MHy4 = MetaAdapterFactory.getContainmentLink(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x2e66f9a613f69c80L, 0x2e66f9a613f69c87L, "docs");
    /*package*/ static final SReferenceLink event$PJOt = MetaAdapterFactory.getReferenceLink(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x2e66f9a613f69c83L, 0x2e66f9a613f69cbaL, "event");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept DESModel$DK = MetaAdapterFactory.getConcept(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x1ada9a09174c9630L, "SimpleDES.structure.DESModel");
    /*package*/ static final SConcept ExternalFunction$U_ = MetaAdapterFactory.getConcept(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x6f36cc77d0c6228bL, "SimpleDES.structure.ExternalFunction");
    /*package*/ static final SConcept Argument$9m = MetaAdapterFactory.getConcept(0x6d11763d483d4b2bL, 0x8efc09336c1b0001L, 0x6d872ef9245a20d7L, "com.mbeddr.core.modules.structure.Argument");
    /*package*/ static final SConcept EventHandler$Ov = MetaAdapterFactory.getConcept(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x2dc3a690836fd0d0L, "SimpleDES.structure.EventHandler");
    /*package*/ static final SConcept EventDefinition$wO = MetaAdapterFactory.getConcept(0xc4765525912b41b9L, 0xace4ce3b88117666L, 0x2e66f9a613f69c80L, "SimpleDES.structure.EventDefinition");
  }
}
