package ReversibleStatements.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AbstractItem = 0;
  public static final int AnyNodeItem = 1;
  public static final int ArbitraryFunctionCall = 2;
  public static final int ArbitraryTextAttributePrefix = 3;
  public static final int ArbitraryTextExpression = 4;
  public static final int ArbitraryTextItem = 5;
  public static final int ArbitraryTextType = 6;
  public static final int ArgumentRef = 7;
  public static final int BreakStatement = 8;
  public static final int CheckpointLocalVarRef = 9;
  public static final int CommentStatement = 10;
  public static final int CommentedElseIfPart = 11;
  public static final int CommentedElsePart = 12;
  public static final int CommentedStatement = 13;
  public static final int CommentedSwitchMember = 14;
  public static final int ContinueStatement = 15;
  public static final int DesignatedInitializer = 16;
  public static final int DoWhileStatement = 17;
  public static final int ElseIfPart = 18;
  public static final int ElsePart = 19;
  public static final int ExpressionStatement = 20;
  public static final int ForStatement = 21;
  public static final int ForVarDecl = 22;
  public static final int ForVarRef = 23;
  public static final int IAllowsIncompleteTypes = 24;
  public static final int IBreakContainer = 25;
  public static final int ICFGNode = 26;
  public static final int ICFGRelevantNode = 27;
  public static final int ICanBeStoredInRegister = 28;
  public static final int IForLike = 29;
  public static final int IHasPrefixes = 30;
  public static final int IIndependentInitExpression = 31;
  public static final int IInitAwareType = 32;
  public static final int ILocalVarScopeProvider = 33;
  public static final int ILoopStatement = 34;
  public static final int IReversible = 35;
  public static final int IReversibleLoop = 36;
  public static final int IStatmentListContainer = 37;
  public static final int IStructuredInitExpression = 38;
  public static final int ITypeContainingType = 39;
  public static final int IValueLike = 40;
  public static final int IfStatement = 41;
  public static final int InitExpression = 42;
  public static final int Iterator = 43;
  public static final int LocalVarRef = 44;
  public static final int LocalVariableDeclaration = 45;
  public static final int NotParsedStatement = 46;
  public static final int PragmaStatement = 47;
  public static final int Prefix = 48;
  public static final int ReturnStatement = 49;
  public static final int ReversibleStatement = 50;
  public static final int ReversibleStatementList = 51;
  public static final int SimpleAttributePrefix = 52;
  public static final int SwitchCase = 53;
  public static final int SwitchDefault = 54;
  public static final int SwitchMember = 55;
  public static final int SwitchStatement = 56;
  public static final int WaitBusy = 57;
  public static final int WhileStatement = 58;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xf75f9e3fb00b4997L, 0x8af20a8ce6b25221L);
    builder.put(0xa59139396a1f537L, AbstractItem);
    builder.put(0xa59139396a1f538L, AnyNodeItem);
    builder.put(0x2b2330fc37afffadL, ArbitraryFunctionCall);
    builder.put(0x4c1f010ea29d7fb6L, ArbitraryTextAttributePrefix);
    builder.put(0x352a4cc97cbc26a6L, ArbitraryTextExpression);
    builder.put(0x352a4cc97cbc4609L, ArbitraryTextItem);
    builder.put(0x30fcd439b3a3318cL, ArbitraryTextType);
    builder.put(0x586abb2d564e82ffL, ArgumentRef);
    builder.put(0x7525a1fdf25d5076L, BreakStatement);
    builder.put(0x571ea5ef247e3b6dL, CheckpointLocalVarRef);
    builder.put(0x174e9d736105b2d8L, CommentStatement);
    builder.put(0x320e0fd638813d3L, CommentedElseIfPart);
    builder.put(0x320e0fd63385fefL, CommentedElsePart);
    builder.put(0x617d88a37ecb3342L, CommentedStatement);
    builder.put(0x16fdbcc716a17bbeL, CommentedSwitchMember);
    builder.put(0x70db34ef88f3c10bL, ContinueStatement);
    builder.put(0x180c2851fde77716L, DesignatedInitializer);
    builder.put(0x7525a1fdf25de2ccL, DoWhileStatement);
    builder.put(0x2b8026b23bc272a6L, ElseIfPart);
    builder.put(0x14bcec604136b8e6L, ElsePart);
    builder.put(0x64ae61a4018a8592L, ExpressionStatement);
    builder.put(0x64ae61a40186e676L, ForStatement);
    builder.put(0x64ae61a401870e23L, ForVarDecl);
    builder.put(0x347479252a95b28aL, ForVarRef);
    builder.put(0x6602642fc0a74a1dL, IAllowsIncompleteTypes);
    builder.put(0x7525a1fdf25d507dL, IBreakContainer);
    builder.put(0x2c099870ae399b42L, ICFGNode);
    builder.put(0x2c099870ae49805fL, ICFGRelevantNode);
    builder.put(0x509503be9ecc5d25L, ICanBeStoredInRegister);
    builder.put(0xff8c67694eff734L, IForLike);
    builder.put(0x866dc95fc7a033eL, IHasPrefixes);
    builder.put(0x52bfade908143913L, IIndependentInitExpression);
    builder.put(0x7ad4c4c8a2db08a4L, IInitAwareType);
    builder.put(0x1d0c3765e2e2fcf8L, ILocalVarScopeProvider);
    builder.put(0x7b54acc4750283c3L, ILoopStatement);
    builder.put(0x56ee1731ff59bedbL, IReversible);
    builder.put(0x6337a44ca461bdf4L, IReversibleLoop);
    builder.put(0x5f5c402aa7667ef3L, IStatmentListContainer);
    builder.put(0x391df9e40e14d64cL, IStructuredInitExpression);
    builder.put(0x6bbcdccef5e46755L, ITypeContainingType);
    builder.put(0x4ba188b8c52b0074L, IValueLike);
    builder.put(0x5718179e5b1bb7d7L, IfStatement);
    builder.put(0x7ad4c4c8a2db08a1L, InitExpression);
    builder.put(0x347479252a927246L, Iterator);
    builder.put(0x1d0c3765e2e1d67aL, LocalVarRef);
    builder.put(0x3a16e3a9c7ad96e6L, LocalVariableDeclaration);
    builder.put(0x242458b0b38bd8cfL, NotParsedStatement);
    builder.put(0xb9b8155bc8b14deL, PragmaStatement);
    builder.put(0x866dc95fc7a033fL, Prefix);
    builder.put(0x4b1eecbba5015fabL, ReturnStatement);
    builder.put(0x3a16e3a9c7ad6d03L, ReversibleStatement);
    builder.put(0x3a16e3a9c7ad9955L, ReversibleStatementList);
    builder.put(0x7853fc2bcf81183dL, SimpleAttributePrefix);
    builder.put(0x2b8026b23bc2da00L, SwitchCase);
    builder.put(0x2b8026b23bc2da02L, SwitchDefault);
    builder.put(0x2b8026b23bc2d9feL, SwitchMember);
    builder.put(0x2b8026b23bc2d9fcL, SwitchStatement);
    builder.put(0x73802639eda97c80L, WaitBusy);
    builder.put(0x7525a1fdf25beef2L, WhileStatement);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
