package ReversibleExpressions.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;

public class GeneratedNodeSubstituteActions_Contribution extends SubstituteMenuBase {
  public GeneratedNodeSubstituteActions_Contribution() {
    super(true, new EditorMenuDescriptorBase("contribution to the " + "default substitute menu for " + "BaseConcept", new SNodePointer("r:e9706a5f-6192-4ab2-9fe9-9e1d284b7670(ReversibleExpressions.editor)", "2531002643696496768")));
  }

}
