package ReversibleExpressions.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import jetbrains.mps.lang.editor.menus.substitute.ConstraintsFilteringSubstituteMenuPartDecorator;
import jetbrains.mps.lang.editor.menus.substitute.ReferenceScopeSubstituteMenuPart;
import jetbrains.mps.lang.editor.menus.ConceptMenusPart;
import java.util.Collection;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.editor.menus.substitute.DefaultSubstituteMenuLookup;
import jetbrains.mps.smodel.language.LanguageRegistry;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class GlobalConstantRef_SubstituteMenu extends SubstituteMenuBase {
  public GlobalConstantRef_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for GlobalConstantRef. Generated from implicit smart reference attribute.", new SNodePointer("r:539823a2-87c6-4a7e-abc8-d6fc586848eb(ReversibleExpressions.structure)", "5666369706459453176")));
  }
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new ConstraintsFilteringSubstituteMenuPartDecorator(new SMP_ReferenceScope_lv09ly_a(), CONCEPTS.GlobalConstantRef$PE));
    result.add(new SMP_Subconcepts_lv09ly_b());
    return result;
  }

  public class SMP_ReferenceScope_lv09ly_a extends ReferenceScopeSubstituteMenuPart {

    public SMP_ReferenceScope_lv09ly_a() {
      super(CONCEPTS.GlobalConstantRef$PE, LINKS.constant$ODeS, new EditorMenuDescriptorBase("reference scope substitute menu part", null));
    }

  }
  public class SMP_Subconcepts_lv09ly_b extends ConceptMenusPart<SubstituteMenuItem, SubstituteMenuContext> {
    public SMP_Subconcepts_lv09ly_b() {
      super(new EditorMenuDescriptorBase("include menus for all the direct subconcepts of " + "GlobalConstantRef", null));
    }

    @Override
    protected Collection<SAbstractConcept> getConcepts(final SubstituteMenuContext _context) {
      return getDirectDescendants(_context, CONCEPTS.GlobalConstantRef$PE);
    }

    @Override
    protected Collection<SubstituteMenuItem> createItemsForConcept(SubstituteMenuContext context, SAbstractConcept concept) {
      return context.createItems(new DefaultSubstituteMenuLookup(LanguageRegistry.getInstance(context.getEditorContext().getRepository()), concept));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept GlobalConstantRef$PE = MetaAdapterFactory.getConcept(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x4ea2fd39ef8cd6f8L, "ReversibleExpressions.structure.GlobalConstantRef");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink constant$ODeS = MetaAdapterFactory.getReferenceLink(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x4ea2fd39ef8cd6f8L, 0x4ea2fd39ef8cd6faL, "constant");
  }
}
