package ReversibleExpressions.editor;

/*Generated by MPS */

import jetbrains.mps.lang.editor.generator.internal.AbstractCellMenuComponent;
import jetbrains.mps.nodeEditor.cellMenu.SubstituteInfoPartExt;
import jetbrains.mps.lang.editor.generator.internal.AbstractCellMenuPart_Generic_Group;
import java.util.List;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.model.SModel;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.action.SNodeFactoryOperations;
import ReversibleExpressions.actions.ExpressionTreeRebalancingHelper;
import jetbrains.mps.openapi.editor.menus.EditorMenuDescriptor;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class replace_withAnotherBinaryExpression extends AbstractCellMenuComponent {
  public replace_withAnotherBinaryExpression() {
    super(new SubstituteInfoPartExt[]{new BinaryExpression_generic_cellMenu_bcxgj9_a0()});
  }
  public static class BinaryExpression_generic_cellMenu_bcxgj9_a0 extends AbstractCellMenuPart_Generic_Group {
    public BinaryExpression_generic_cellMenu_bcxgj9_a0() {
    }

    protected List<?> createParameterObjects(SNode node, EditorContext editorContext) {
      return SConceptOperations.getAllSubConcepts2(CONCEPTS.BinaryExpression$b, SNodeOperations.getModel(node));

    }
    protected void handleAction(Object parameterObject, SNode node, SModel model, EditorContext editorContext) {
      this.handleAction_impl((SConcept) parameterObject, node, model, editorContext);
    }
    private void handleAction_impl(SConcept parameterObject, SNode node, SModel model, EditorContext editorContext) {
      SNode newInstance = SNodeFactoryOperations.createNewNode(parameterObject, node);
      SNodeOperations.replaceWithAnother(node, newInstance);
      ExpressionTreeRebalancingHelper.demandRebalanceTree(newInstance);
    }
    protected boolean isReferentPresentation() {
      return false;
    }

    @Override
    protected EditorMenuDescriptor getEditorMenuDescriptor(Object parameterObject) {
      return new EditorMenuDescriptorBase("generic group with parameter: " + ((parameterObject == null ? "null" : parameterObject.toString())), new SNodePointer("r:e9706a5f-6192-4ab2-9fe9-9e1d284b7670(ReversibleExpressions.editor)", "4420643699735282056"));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept BinaryExpression$b = MetaAdapterFactory.getConcept(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x7af69e2e83a1ba34L, "ReversibleExpressions.structure.BinaryExpression");
  }
}
