package ReversibleFunctions.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;

public class EmptyLine_SubstituteMenu extends SubstituteMenuBase {
  public EmptyLine_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for " + "EmptyLine", new SNodePointer("r:bf26afff-5aa1-49e0-91f3-7e019227c87a(ReversibleFunctions.editor)", "3415911555223858975")));
  }

}
