package ReversibleExpressions.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class CommentedContent_Constraints extends BaseConstraintsDescriptor {
  /*package*/ CommentedContent_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.CommentedContent$YK, initContext);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept CommentedContent$YK = MetaAdapterFactory.getConcept(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x1f49de97a1082b73L, "ReversibleExpressions.structure.CommentedContent");
  }
}
