package ReversibleExpressions.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SNodePointer;
import java.util.regex.Pattern;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class HexNumberLiteral_Constraints extends BaseConstraintsDescriptor {
  /*package*/ HexNumberLiteral_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.HexNumberLiteral$Sr, initContext);
    record(new Value_PD(this));
  }

  /*package*/ static final class Value_PD extends BasePropertyConstraintsDescriptor {
    public Value_PD(ConstraintsDescriptor container) {
      super(PROPS.value$jw9Y, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castString(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:e81df3c1-b167-4843-95a2-4c0dd8e517e2(ReversibleExpressions.constraints)", "1054289341113450473"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, String propertyValue) {
      return propertyValue.length() <= 16 && (REGEXP.matcher(propertyValue).matches());

    }
  }
  private static final Pattern REGEXP = Pattern.compile("[0-9a-fA-F]+", 0);

  private static final class CONCEPTS {
    /*package*/ static final SConcept HexNumberLiteral$Sr = MetaAdapterFactory.getConcept(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0xea19691e38c3fccL, "ReversibleExpressions.structure.HexNumberLiteral");
  }

  private static final class PROPS {
    /*package*/ static final SProperty value$jw9Y = MetaAdapterFactory.getProperty(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x1eb611a68febd3e5L, 0x1eb611a68fec38b0L, "value");
  }
}
