package ReversibleExpressions.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Literal_Constraints extends BaseConstraintsDescriptor {
  /*package*/ Literal_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.Literal$Vh, initContext);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Literal$Vh = MetaAdapterFactory.getConcept(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x7af69e2e83a1ba5aL, "ReversibleExpressions.structure.Literal");
  }
}
