package ReversibleExpressions.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.ConstraintFunction;
import jetbrains.mps.smodel.runtime.ConstraintContext_CanBeParent;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class UnaryPrePosModificationExpression_Constraints extends BaseConstraintsDescriptor {
  /*package*/ UnaryPrePosModificationExpression_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.UnaryPrePosModificationExpression$3r, initContext);
    setCanBeParent(new ConstraintFunction<ConstraintContext_CanBeParent, Boolean>() {
      @NotNull
      public Boolean invoke(@NotNull ConstraintContext_CanBeParent context, @Nullable CheckingNodeContext checkingNodeContext) {
        boolean result = staticCanBeAParent(context.getNode(), context.getChildNode(), context.getChildConcept(), context.getLink());

        if (!(result) && checkingNodeContext != null) {
          checkingNodeContext.setBreakingNode(canBeParentBreakingPoint);
        }

        return result;
      }
    });
  }

  private static boolean staticCanBeAParent(SNode node, SNode childNode, SAbstractConcept childConcept, SContainmentLink link) {
    return ListSequence.fromList(SNodeOperations.getNodeDescendants(childNode, CONCEPTS.UnaryPrePosModificationExpression$3r, true, new SAbstractConcept[]{})).isEmpty();
  }
  private static final SNodePointer canBeParentBreakingPoint = new SNodePointer("r:e81df3c1-b167-4843-95a2-4c0dd8e517e2(ReversibleExpressions.constraints)", "8237807170236145684");

  private static final class CONCEPTS {
    /*package*/ static final SConcept UnaryPrePosModificationExpression$3r = MetaAdapterFactory.getConcept(0x9abffa92487542bfL, 0x9379c4f95eb496d4L, 0x632cdd5acfb8529eL, "ReversibleExpressions.structure.UnaryPrePosModificationExpression");
  }
}
